### ISSUE TITLE
Use `globalSetup` instead of `setupFiles`

### ISSUE THREAD

**Issue by ghost** [capaj/set-tz#2]
First of all, great tool!

Somehow calling `set-tc/utc` in `setupFiles` doesn't work for me. I put this inside `globalSetup` then it works great. This is similar to this https://stackoverflow.com/a/56482581/605840

My env:
- OSX High Sierra 10.13.5
- jest@^23.6.0
- set-tz@0.2.0
- Machine time zone: +0800

**Comment by capaj** [comment]
thanks for reporting! tweaked the readme.
